name: assimp

on:
  push:
    paths:
      - .github/workflows/assimp.yml
      - assimp/**

jobs:
  ci:
    permissions:
      contents: write
    uses: ./.github/workflows/_build.yml
    with: { lib: assimp, version: v1.0 }
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
