name: glfw

on:
  push:
    paths:
      - glfw/**
      - .github/workflows/glfw.yml
jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: {
        lib: glfw,
        version: v1.0,
        # multistrap: true,
        # those are needed for emscripten. only the libxrandr-dev , doesnt hurt add to all linux plats (xorg-dev libglu1-mesa-dev libxrandr-dev)
        linux_apt: libwayland-dev libxkbcommon-dev libx11-dev xorg-dev libglu1-mesa-dev cmake extra-cmake-modules libxrandr-dev,
      }
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
