name: opencv-dnn
# bump 2026-06-28: re-trigger at HEAD to pick up zlib-ng utils fix
on:
  push:
    paths:
      - .github/workflows/opencv-dnn.yml
      - opencv-dnn/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: opencv-dnn, version: add }
    secrets: inherit
