name: poco

on:
  push:
    paths:
      - poco/**
      - .github/workflows/poco.yml

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: poco, version: add, linux_apt: libssl-dev }
    secrets: inherit
  android:
    permissions:
      contents: write
    uses: ./.github/workflows/_build_android.yml
    with: { lib: poco, version: add }
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
