name: pugixml
# 008

on:
  push:
    paths:
      - pugixml/**
      - .github/workflows/pugixml.yml

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with:
      lib: pugixml
      version: v1.0
      platforms: >-
        [
          {"platform":"linux64","os":"ubuntu-22.04","toolchain":"llvm"},
          {"platform":"macos","os":"macos-26","toolchain":"apple-llvm"},
          {"platform":"vs","os":"windows-2022","toolchain":"vs-stable"},
          {"platform":"rpi-aarch64","os":"ubuntu-22.04-arm","prefix":"aarch64-linux-gnu","toolchain":"aarch64-linux-gnu-gcc-12"},
          {"platform":"emscripten","os":"ubuntu-latest","toolchain":"emscripten"},
          {"platform":"android-arm64","os":"ubuntu-22.04","toolchain":"llvm","android_abi":"arm64-v8a"},
          {"platform":"android-armv7","os":"ubuntu-22.04","toolchain":"llvm","android_abi":"armeabi-v7a"},
          {"platform":"android-x86","os":"ubuntu-22.04","toolchain":"llvm","android_abi":"x86"},
          {"platform":"android-x86_64","os":"ubuntu-22.04","toolchain":"llvm","android_abi":"x86_64"}
        ]
      linux_apt: libx11-dev libglu1-mesa-dev libgl1-mesa-dev libwayland-dev libxkbcommon-dev xorg-dev libegl1-mesa-dev libopengl-dev libglx-dev libglvnd-dev
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
