name: rtAudio

on:
  push:
    paths:
      - rtAudio/**
      - .github/workflows/rtAudio.yml

jobs:
  ci:
    permissions:
      contents: write

    # uses: ./.github/workflows/_buildnoemscripten.yml
    uses: ./.github/workflows/_build.yml
    with: {
        lib: rtAudio,
        version: v1.0,
        # multistrap: true,
        linux_apt: jackd libpulse-dev libasound2-dev,
      }
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
