name: yaml-cpp
# 001

on:
  push:
    paths:
      - .github/workflows/yaml-cpp.yml
      - yaml-cpp/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: yaml-cpp, version: v1.0 }
    secrets: inherit
# bump 2026-07-24: rebuild on windows-2022 (MSVC 14.4x) runner pin
